### ISSUE TITLE
Facing issue like kindly make sure to use  our properly licensed chrome extension at NeoColab platform.

### ISSUE THREAD

**Issue by justabhioffficial** [sr2echa/thottathukiduven-v2#3]
Facing issue like kindly make sure to use  our properly licensed chrome extension at NeoColab platform.
![WhatsApp Image 2024-10-19 at 11 09 07_df2fa3b8](https://github.com/user-attachments/assets/523363a5-6a3a-4ce0-a9e9-793da7025527)
![WhatsApp Image 2024-10-19 at 11 09 07_df2fa3b8](https://github.com/user-attachments/assets/83ab33f9-5ff7-4140-8511-6f4c65898631)

**Comment by HariVimal-RSM** [comment]
yes

**Comment by ghost** [comment]
still facing the same issue. Please help me resolve it as my exams are near

**Comment by sr2echa** [comment]
The issue has been patched now : )
